create:
  path: /
  controller: App\Controller\Api\EventActivityApiController::create
  methods: ['POST']

get:
  path: /{id}
  controller: App\Controller\Api\EventActivityApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\EventActivityApiController::list
  methods: ['GET']

remove:
  path: /{id}
  controller: App\Controller\Api\EventActivityApiController::remove
  methods: ['DELETE']

update:
  path: /{id}
  controller: App\Controller\Api\EventActivityApiController::update
  methods: ['PATCH']
