list:
  path: /
  controller: App\Controller\Web\Admin\OpportunityAdminController::list
  methods: ['GET']

edit:
  path: /editar/{id}
  controller: App\Controller\Web\Admin\OpportunityAdminController::edit
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\OpportunityAdminController::remove
  methods: ['GET']
