create:
  path: /adicionar
  controller: App\Controller\Web\Admin\TagAdminController::create
  methods: ['GET', 'POST']

list:
  path: /
  controller: App\Controller\Web\Admin\TagAdminController::list
  methods: ['GET']

remove:
  path: /{id}/remover
  controller: App\Controller\Web\Admin\TagAdminController::remove
  methods: ['GET']

edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\TagAdminController::edit
  methods: ['GET', 'POST']
